name: Build and Test
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
      solution_file:
        required: true
        type: string

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Build
      run: >
        dotnet build ${{ inputs.solution_file }}
        --configuration Release
        --no-restore
    - name: Test
      run: >
        dotnet test ${{ inputs.solution_file }}
        --configuration Release
        --verbosity normal
        --no-build
        --nologo
        --collect "Code Coverage"
        --settings .runsettings
        --results-directory ./bin/TestResults
        --logger GitHubActions
