name: Build and Test
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest
        description: 'The os to run the runner on'
      dotnet_version:
        required: true
        type: string
        description: 'The dotnet version to use'
      solution_file:
        required: true
        type: string
        description: 'The full name of the solution file'

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Setup github remotes
      run: >
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        --username ${{ github.repository_owner }}
        --password "$GITHUB_TOKEN"
        --store-password-in-clear-text
        --name github
      shell: bash
    - name: Install dependencies
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Build
      run: >
        dotnet build ${{ inputs.solution_file }}
        --configuration Release
        --no-restore
    - name: Test
      run: >
        dotnet test ${{ inputs.solution_file }}
        --configuration Release
        --verbosity normal
        --no-build
        --nologo
        --filter FullyQualifiedName!~IntegrationTests
        --collect "Code Coverage"
        --settings .runsettings
        --logger GitHubActions
