name: Create github release
on:
  workflow_call:
  
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  release:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: write
    steps:
      - name: "Create release"
        env:
          tag: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create "$tag"
          --repo="$GITHUB_REPOSITORY"
          --title="${GITHUB_REPOSITORY#*/} ${tag#v}"
          --generate-notes
