name: Deploy package to Nuget and Github
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
        description: 'The os to run the runner on'
      dotnet_version:
        required: true
        type: string
        description: 'The dotnet version to use'
      solution_file:
        required: true
        type: string
        description: 'The full name of the solution file'
    secrets:
      NUGET_KEY:
        required: false
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  deploy:
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    runs-on: ${{ inputs.os }}
    permissions:
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Setup github remotes
      run: >
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        --username ${{ github.repository_owner }}
        --password "$GITHUB_TOKEN"
        --store-password-in-clear-text
        --name github
      shell: bash
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: Install dependencies
      run: dotnet restore ${{ inputs.solution_file }}
    - name: Pack
      run: >
        dotnet pack ${{ inputs.solution_file }}
        --configuration Release
        --verbosity normal
        --nologo
        --no-restore
        /p:Version=${{ env.NBGV_SemVer2 }}
        --output ./bin/Pack/
    - name: Push to GitHub Feed
      run: >
        dotnet nuget push ./bin/Pack/*.nupkg
        --source "github"
        --skip-duplicate
        --api-key "$GITHUB_TOKEN"
      shell: bash
    - name: Validate nuget key
      if: env.NUGET_KEY == ''
      run: echo "::warning::'NUGET_KEY' has not been set, go to 'settings \> secrets \> actions' to create it"
    - name: Push to NuGet Feed
      if: env.NBGV_PublicRelease == 'true' && env.NUGET_KEY != ''
      run: >
        dotnet nuget push ./bin/Pack/*.nupkg
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate
        --api-key "$NUGET_KEY"
      shell: bash
